### ISSUE TITLE
Cant start because some OpenGL Error

### ISSUE THREAD

**Issue by ghost** [BiggerSeries/Quartz#10]
Hey Guys!

i wanted to play TNP Limitless 6 so i installed it via prism launcher and it is just crashing because some quartz open gl error, heres the logs:
Prism Log: https://mclo.gs/1Z58Ciy
Lates Log: https://mclo.gs/Owz2Ju8
Debug Log: https://mclo.gs/pBQhGgn
hs_err_pid: https://mclo.gs/wzC9DvH

**Comment by ghost** [comment]
Also here the Crash Log: https://mclo.gs/5u8EfzD

**Comment by RogueLogix** [comment]
Can you try removing biggerreactors and quartz and see if you will get the same native crash.
the first four logs are all the same native level crash in GLFW, but the 5th one appears to be completely unrelated.

**Comment by tinypanda31** [comment]
Im continuing to have the same issue with this pack even after disabling those 2 mods, im a bit lost here lol
logs: https://mclo.gs/0iwUf6J

**Comment by RogueLogix** [comment]
Given that the error can replicate without these mods present, and I've seen no other reports of it since. I'm going to close this. If this issue does persist the issue can be re-opened.
