### ISSUE TITLE
OpenGL-related crash TNP Limitless 6

### ISSUE THREAD

**Issue by rallias** [BiggerSeries/Quartz#13]
latest.log: https://mclo.gs/sB6FKnC
hs_err_pid1521941.log: https://mclo.gs/IaiEf9R

**Comment by RogueLogix** [comment]
What GPU and what driver were you using? I believe I've had this mentioned elsewhere with Nvidia cards.

**Comment by RogueLogix** [comment]
closing as stale, if it happens again or if someone else has the same issue, open a new issue
