### ISSUE TITLE
Empty Creative tab

### ISSUE THREAD

**Issue by txnitxnichopper** [BiggerSeries/Quartz#15]
![image](https://github.com/BiggerSeries/Quartz/assets/67132971/14021eb3-6557-459b-aa0a-b8c544eebc33)

**Comment by RogueLogix** [comment]
https://github.com/BiggerSeries/Quartz/issues/11

Demo/test block has also been added in 1.20.1.

**Comment by txnitxnichopper** [comment]
bruh you don't need a whole creative mode tab for a development block in a library mod, it's completely empty in 1.19, and it doesn't even have a lang entry. Please fix this

**Comment by RogueLogix** [comment]
1.18 too, this is not getting fixed. Its very minor at best, just ignore the tab.

**Comment by txnitxnichopper** [comment]
"just ignore the tab" is not a solution. You don't even have a lang entry, so you're not even registering the tab properly.

**Comment by RogueLogix** [comment]
No, its registered properly, quartz just didn't have any lang file at all. There is one now https://github.com/BiggerSeries/Quartz/commit/6136283cc060040d80bb4733aaf99f98b459d414
