### ISSUE TITLE
[1.20.1] Rendering overlay crash on boot with Rubidium. (Forge Sodium port).

### ISSUE THREAD

**Issue by Gbergz** [BiggerSeries/Quartz#16]
Title ^

### **Versions:**
Minecraft 1.20.1
Forge: 47.1.0
Quartz: 0.2.0-alpha
Phosphyllite: 0.7.0-alpha
Bigger Reactors: 0.6.0-beta.10

Crash-Report: https://gist.githubusercontent.com/Gbergz/3e4a1e624fbc1e385fe3c61fe034213f/raw/2efc9c893d9ec3002287c61dca1f754c806642d5/gistfile1.txt

**Comment by RogueLogix** [comment]
Issue on Sodium's side, there is an open PR to fix it, should be in the next release of Sodium.
https://github.com/CaffeineMC/sodium-fabric/pull/1842

**Comment by RogueLogix** [comment]
Sodium PR has been merged, still need the Sodium release and Rubidium port though

**Comment by RogueLogix** [comment]
Rubidium update is out, and has fixed this issue.
