### ISSUE TITLE
Quartz startup failed

### ISSUE THREAD

**Issue by alexytomi** [BiggerSeries/Quartz#17]
https://pastebin.com/raw/pv2WMHuy

I've been trying to run the mod on my phone. Zink should support the apparently missing extension, was told to ask here as the log states so.

**Comment by alexytomi** [comment]
If there's any way to turn off or skip the extension checks, that would be great

**Comment by RogueLogix** [comment]
there is not

**Comment by alexytomi** [comment]
Thanks for the response and not deleting this thread. Updating the zink renderer solves the issue.


![Screenshot_20230824_203636_PojavLauncher (Minecraft Java Edition for Android).jpg](https://github.com/BiggerSeries/Quartz/assets/60690056/9b982a64-b3db-4a54-af71-2091da87befb)

The updated zink is from a fork and is not official.
 https://github.com/SolDev69/PojavLauncher/actions/workflows/android.yml?query=branch%3Av3_zink_updated

**Comment by alexytomi** [comment]
After some more investigation it seems zink wasn't updated. I don't know what caused the issue, very odd. This workaround works though for some reason.

Despite only touching the vulkan drivers of adreno gpus to support all of zink, it also affected my mali gpu

**Comment by alexytomi** [comment]
Sorry forgot to close this, the issue isn't an issue anymore
