### ISSUE TITLE
Incompatibility with Rubidium (1.20.1, latest)

### ISSUE THREAD

**Issue by StellarRemnants** [BiggerSeries/Quartz#18]
The latest versions of Quartz (0.2.0-alpha) and Rubidium (0.6.5) for Minecraft version 1.20.1 appear to have a fatal incompatibility (see attached crash log below) on the latest version of forge (47.1.44). 

Minimum reproducible environment:
FML v47.1.44
Rubidium v0.6.5
Phosphophyllite v0.7.0-alpha
Quartz v0.2.0-alpha
 
Throws exception:

```
Description: Rendering overlay

java.lang.ClassCastException: class net.roguelogix.quartz.internal.common.InternalMesh$Builder$BufferBuilder cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter (net.roguelogix.quartz.internal.common.InternalMesh$Builder$BufferBuilder is in module quartz@0.2.0-alpha of loader 'TRANSFORMER' @1d858300; me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter is in module rubidium@0.6.5 of loader 'TRANSFORMER' @1d858300)
```

[crash-2023-08-30_19.56.53-client.txt](https://github.com/BiggerSeries/Quartz/files/12481785/crash-2023-08-30_19.56.53-client.txt)

**Comment by RogueLogix** [comment]
https://github.com/BiggerSeries/Quartz/issues/16
