### ISSUE TITLE
Cannot start with Holy renderer

### ISSUE THREAD

**Issue by NanaAkira73** [BiggerSeries/Quartz#27]
The minecraft launcher on mobile phone cannot start this mod with Holy renderer,it is a OpenGL 2.1 renderer.And the launcher i used is FCL(Fold Craft Launcher).

**Comment by RogueLogix** [comment]
Only officially supported platforms are supported. Please use a normal computer or play pocket edition

**Comment by NanaAkira73** [comment]
> Only officially supported platforms are supported. Please use a normal computer or play pocket edition

I think it is not bad to play Minecraft:Java Edition any time,any where.
