### ISSUE TITLE
ATM 7 + Rubidium RenderType crash

### ISSUE THREAD

**Issue by JonaszRohde** [BiggerSeries/Quartz#6]
Game crashed right after completing the turbine.
[crash-2022-06-03_17.48.31-client.txt](https://github.com/BiggerSeries/BiggerReactors/files/8833922/crash-2022-06-03_17.48.31-client.txt)

**Comment by JonaszRohde** [comment]
Okay I found the solution. It's because of the Oculus mod. It causes a crash even when you don't have any shaders enabled.

**Comment by RogueLogix** [comment]
This is actually something I planned to fix, but there wasn't a github issue for it

**Comment by RogueLogix** [comment]
As far as I am aware, this is no longer an issue, with the cause being removed on my side in 1.20.1
