### ISSUE TITLE
[1.19.2] Attempt to use phosphophyllite before checking version compatibility

### ISSUE THREAD

**Issue by Zelioth** [BiggerSeries/Quartz#8]
Updating my mod pack to latest forge and mod versions and I seen Phos. updated this morning. 

When using forge version 43.2.0 and updating to 0.6.0 Beta 6 it seems to crash on startup each time. 

Will place crash reports. 
[crash-2022-12-11_13.34.50-client.txt](https://github.com/BiggerSeries/Phosphophyllite/files/10203084/crash-2022-12-11_13.34.50-client.txt)
[latest.log](https://github.com/BiggerSeries/Phosphophyllite/files/10203086/latest.log)

**Comment by RogueLogix** [comment]
the update isn't broken, Quartz just isn't checking the version before trying to do something, where i did make a breaking change in phos, before the version check happens.

I haven't pushed updated versions of Quartz/BiR yet, this update was pushed for Resourceful Bees, new versions of Quartz and BiR should be out soon.

**Comment by RogueLogix** [comment]
crashing fixed with https://github.com/BiggerSeries/Quartz/commit/16de6ca830bc85e865ebb393db3d8a2539a9e4ff, will be pushed in next version.
